In [17]:
import pandas as pd

In [18]:
df = pd.read_csv('uber-raw-data-janjune-15.csv')

In [19]:
df

,Dispatching_base_num,Pickup_date,Affiliated_base_num,locationID
0,B02617,2015-05-17 09:47:00,B02617,141
1,B02617,2015-05-17 09:47:00,B02617,65
2,B02617,2015-05-17 09:47:00,B02617,100
3,B02617,2015-05-17 09:47:00,B02774,80
4,B02617,2015-05-17 09:47:00,B02617,90
5,B02617,2015-05-17 09:47:00,B02617,228
6,B02617,2015-05-17 09:47:00,B02617,7
7,B02617,2015-05-17 09:47:00,B02764,74
8,B02617,2015-05-17 09:47:00,B02617,249
9,B02617,2015-05-17 09:47:00,B02764,22
10,B02617,2015-05-17 09:48:00,B02617,263
11,B02617,2015-05-17 09:48:00,B02617,61
12,B02617,2015-05-17 09:49:00,B02617,229
13,B02617,2015-05-17 09:49:00,B02617,164
14,B02617,2015-05-17 09:49:00,B02617,237
15,B02617,2015-05-17 09:49:00,B02617,142
16,B02617,2015-05-17 09:49:00,B02617,188
17,B02617,2015-05-17 09:49:00,B02617,237
18,B02617,2015-05-17 09:49:00,B02617,224
19,B02617,2015-05-17 09:49:00,B02617,238
20,B02617,2015-05-17 09:49:00,B02682,242
21,B02617,2015-05-17 09:50:00,B02617,95
22,B02617,2015-05-17 09:50:00,B02617,141
23,B02617,2015-05-17 09:50:00,B02617,236
24,B02617,2015-05-17 09:50:00,B02617,233
25,B02617,2015-05-17 09:50:00,B02617,230
26,B02617,2015-05-17 09:50:00,B02617,162
27,B02617,2015-05-17 09:50:00,B02764,234
28,B02617,2015-05-17 09:50:00,B02617,161
29,B02617,2015-05-17 09:51:00,B02617,87
...,...,...,...,...
14270449,B02765,2015-05-08 15:39:00,B02765,163
14270450,B02765,2015-05-08 15:39:00,B00014,239
14270451,B02765,2015-05-08 15:39:00,B02765,239
14270452,B02765,2015-05-08 15:39:00,B02765,238
14270453,B02765,2015-05-08 15:39:00,B02765,211
14270454,B02765,2015-05-08 15:39:00,B02682,68
14270455,B02765,2015-05-08 15:40:00,B00271,170
14270456,B02765,2015-05-08 15:40:00,B02765,211
14270457,B02765,2015-05-08 15:40:00,B00789,236
14270458,B02765,2015-05-08 15:40:00,B02765,161
14270459,B02765,2015-05-08 15:40:00,B02765,186
14270460,B02765,2015-05-08 15:41:00,B02764,50
14270461,B02765,2015-05-08 15:41:00,B02253,13
14270462,B02765,2015-05-08 15:41:00,B02682,192
14270463,B02765,2015-05-08 15:41:00,B02345,262
14270464,B02765,2015-05-08 15:41:00,B02765,237
14270465,B02765,2015-05-08 15:41:00,B02765,233
14270466,B02765,2015-05-08 15:41:00,B02765,148
14270467,B02765,2015-05-08 15:41:00,B02765,33
14270468,B02765,2015-05-08 15:42:00,B02096,232
14270469,B02765,2015-05-08 15:42:00,B02764,79
14270470,B02765,2015-05-08 15:42:00,B02765,37
14270471,B02765,2015-05-08 15:42:00,B02765,161
14270472,B02765,2015-05-08 15:42:00,B02765,7
14270473,B02765,2015-05-08 15:43:00,B02711,25
14270474,B02765,2015-05-08 15:43:00,B02765,186
14270475,B02765,2015-05-08 15:43:00,B02765,263
14270476,B02765,2015-05-08 15:43:00,B02765,90
14270477,B02765,2015-05-08 15:44:00,B01899,45
14270478,B02765,2015-05-08 15:44:00,B02682,144

In [20]:
dff = pd.read_csv('try.txt',delimiter='\t',names=['locationID','Borough','Area'],header= None)

In [21]:
dff

     locationID        Borough                                 Area
0             2         Queens                          Jamaica Bay
1             3          Bronx              Allerton/Pelham Gardens
2             4      Manhattan                        Alphabet City
3             5  Staten Island                        Arden Heights
4             6  Staten Island              Arrochar/Fort Wadsworth
5             7         Queens                              Astoria
6             8         Queens                         Astoria Park
7             9         Queens                           Auburndale
8            10         Queens                         Baisley Park
9            11       Brooklyn                           Bath Beach
10           12      Manhattan                         Battery Park
11           13      Manhattan                    Battery Park City
12           14       Brooklyn                            Bay Ridge
13           15         Queens              Bay Terrace/Fort Totten
14           16         Queens                              Bayside
15           17       Brooklyn                              Bedford
16           18          Bronx                         Bedford Park
17           19         Queens                            Bellerose
18           20          Bronx                              Belmont
19           21       Brooklyn                     Bensonhurst East
20           22       Brooklyn                     Bensonhurst West
21           23  Staten Island              Bloomfield/Emerson Hill
22           24      Manhattan                         Bloomingdale
23           25       Brooklyn                          Boerum Hill
24           26       Brooklyn                         Borough Park
25           27         Queens  Breezy Point/Fort Tilden/Riis Beach
26           28         Queens              Briarwood/Jamaica Hills
27           29       Brooklyn                       Brighton Beach
28           30         Queens                        Broad Channel
29           31          Bronx                           Bronx Park
..          ...            ...                                  ...
235         237      Manhattan                Upper East Side South
236         238      Manhattan                Upper West Side North
237         239      Manhattan                Upper West Side South
238         240          Bronx                   Van Cortlandt Park
239         241          Bronx                Van Cortlandt Village
240         242          Bronx                 Van Nest/Morris Park
241         243      Manhattan             Washington Heights North
242         244      Manhattan             Washington Heights South
243         245  Staten Island                        West Brighton
244         246      Manhattan            West Chelsea/Hudson Yards
245         247          Bronx                       West Concourse
246         248          Bronx               West Farms/Bronx River
247         249      Manhattan                         West Village
248         250          Bronx        Westchester Village/Unionport
249         251  Staten Island                          Westerleigh
250         252         Queens                           Whitestone
251         253         Queens                        Willets Point
252         254          Bronx             Williamsbridge/Olinville
253         255       Brooklyn            Williamsburg (North Side)
254         256       Brooklyn            Williamsburg (South Side)
255         257       Brooklyn                      Windsor Terrace
256         258         Queens                            Woodhaven
257         259          Bronx                   Woodlawn/Wakefield
258         260         Queens                             Woodside
259         261      Manhattan                   World Trade Center
260         262      Manhattan                       Yorkville East
261         263      Manhattan                       Yorkville West
262         264        Unknown                              Unknown
263         265        Unknown                              Unknown
264           1            EWR                       Newark Airport

[265 rows x 3 columns]

In [22]:
df = df.merge(dff,on='locationID',how='inner')
df

,Dispatching_base_num,Pickup_date,Affiliated_base_num,locationID,Borough,Area
0,B02617,2015-05-17 09:47:00,B02617,141,Manhattan,Lenox Hill West
1,B02617,2015-05-17 09:50:00,B02617,141,Manhattan,Lenox Hill West
2,B02617,2015-05-17 09:53:00,B02617,141,Manhattan,Lenox Hill West
3,B02617,2015-05-17 10:00:00,B02617,141,Manhattan,Lenox Hill West
4,B02617,2015-05-17 10:00:00,B02617,141,Manhattan,Lenox Hill West
5,B02617,2015-05-17 10:03:00,B00272,141,Manhattan,Lenox Hill West
6,B02617,2015-05-17 10:04:00,B02617,141,Manhattan,Lenox Hill West
7,B02617,2015-05-17 10:10:00,B02617,141,Manhattan,Lenox Hill West
8,B02617,2015-05-17 10:17:00,B02617,141,Manhattan,Lenox Hill West
9,B02617,2015-05-17 10:23:00,B02617,141,Manhattan,Lenox Hill West
10,B02617,2015-05-17 10:33:00,B02764,141,Manhattan,Lenox Hill West
11,B02598,2015-01-18 15:15:39,B02598,141,Manhattan,Lenox Hill West
12,B02598,2015-01-18 00:37:16,B02774,141,Manhattan,Lenox Hill West
13,B02598,2015-01-18 18:55:46,B02598,141,Manhattan,Lenox Hill West
14,B02617,2015-05-17 10:58:00,B02617,141,Manhattan,Lenox Hill West
15,B02617,2015-05-17 10:59:00,B02617,141,Manhattan,Lenox Hill West
16,B02617,2015-05-17 11:01:00,B02617,141,Manhattan,Lenox Hill West
17,B02598,2015-01-18 12:31:28,B02774,141,Manhattan,Lenox Hill West
18,B02598,2015-01-18 18:49:03,B02764,141,Manhattan,Lenox Hill West
19,B02598,2015-01-18 06:49:11,B02598,141,Manhattan,Lenox Hill West
20,B02598,2015-01-18 00:45:10,B02617,141,Manhattan,Lenox Hill West
21,B02598,2015-01-18 13:15:42,B02598,141,Manhattan,Lenox Hill West
22,B02617,2015-05-17 11:11:00,B02617,141,Manhattan,Lenox Hill West
23,B02598,2015-01-18 14:41:20,B02598,141,Manhattan,Lenox Hill West
24,B02617,2015-05-17 11:26:00,B02617,141,Manhattan,Lenox Hill West
25,B02617,2015-05-17 11:35:00,B02617,141,Manhattan,Lenox Hill West
26,B02764,2015-03-17 08:28:00,B02764,141,Manhattan,Lenox Hill West
27,B02764,2015-03-17 08:30:00,B02764,141,Manhattan,Lenox Hill West
28,B02764,2015-03-17 08:30:00,B02764,141,Manhattan,Lenox Hill West
29,B02764,2015-03-17 08:30:00,B02764,141,Manhattan,Lenox Hill West
...,...,...,...,...,...,...
14270449,B02512,2015-05-23 02:16:00,B02512,44,Staten Island,Charleston/Tottenville
14270450,B02682,2015-05-02 23:28:00,B02682,44,Staten Island,Charleston/Tottenville
14270451,B02512,2015-06-27 15:13:00,B02512,44,Staten Island,Charleston/Tottenville
14270452,B02598,2015-06-04 09:06:00,B02598,44,Staten Island,Charleston/Tottenville
14270453,B02682,2015-05-08 03:28:00,B02764,44,Staten Island,Charleston/Tottenville
14270454,B02682,2015-03-16 01:12:00,B02682,44,Staten Island,Charleston/Tottenville
14270455,B02764,2015-01-01 22:01:23,B02101,44,Staten Island,Charleston/Tottenville
14270456,B02682,2015-02-06 01:20:44,B02682,44,Staten Island,Charleston/Tottenville
14270457,B02764,2015-05-05 08:05:00,B02764,44,Staten Island,Charleston/Tottenville
14270458,B02765,2015-04-01 14:53:00,B02829,44,Staten Island,Charleston/Tottenville
14270459,B02765,2015-06-18 20:47:00,B02765,44,Staten Island,Charleston/Tottenville
14270460,B02764,2015-05-09 01:32:00,B02764,44,Staten Island,Charleston/Tottenville
14270461,B02765,2015-04-26 00:50:00,B02765,44,Staten Island,Charleston/Tottenville
14270462,B02682,2015-02-19 14:00:02,B02682,2,Queens,Jamaica Bay
14270463,B02682,2015-04-18 11:53:00,B02682,2,Queens,Jamaica Bay
14270464,B02764,2015-04-18 12:28:00,B02764,2,Queens,Jamaica Bay
14270465,B02598,2015-03-27 07:08:00,B02598,2,Queens,Jamaica Bay
14270466,B02764,2015-04-04 15:46:00,B02101,2,Queens,Jamaica Bay
14270467,B02682,2015-06-08 23:23:00,B02682,2,Queens,Jamaica Bay
14270468,B02617,2015-05-10 11:52:00,B02617,2,Queens,Jamaica Bay
14270469,B02765,2015-05-05 13:38:00,B02510,2,Queens,Jamaica Bay
14270470,B02682,2015-05-26 12:02:00,B02682,264,Unknown,Unknown
14270471,B02512,2015-01-24 02:36:12,B02512,264,Unknown,Unknown
14270472,B02512,2015-01-24 02:36:12,B02512,264,Unknown,Unknown
14270473,B02764,2015-04-14 20:00:00,B02764,264,Unknown,Unknown
14270474,B02764,2015-01-18 18:33:32,B02764,264,Unknown,Unknown
14270475,B02682,2015-03-10 09:56:00,B02682,264,Unknown,Unknown
14270476,B02764,2015-02-12 17:21:07,B02518,264,Unknown,Unknown
14270477,B02598,2015-01-08 13:32:45,B00477,110,Staten Island,Great Kills Park
14270478,B02598,2015-04-28 09:15:00,B02598,110,Staten Island,Great Kills Park

In [23]:
df.to_csv('data.csv')

In [13]:
df1 = pd.read_csv('uber-raw-data-apr14.csv')

In [14]:
df2 = pd.read_csv('uber-raw-data-may14.csv')

In [15]:
df3 = pd.read_csv('uber-raw-data-jun14.csv')

In [16]:
df4 = pd.read_csv('uber-raw-data-jul14.csv')

In [17]:
df5 = pd.read_csv('uber-raw-data-aug14.csv')

In [18]:
df6 = pd.read_csv('uber-raw-data-sep14.csv')

In [20]:
df14 = pd.concat([df1,df2,df3,df4,df5,df6])

In [21]:
df14

                  Date/Time      Lat      Lon    Base
0          4/1/2014 0:11:00  40.7690 -73.9549  B02512
1          4/1/2014 0:17:00  40.7267 -74.0345  B02512
2          4/1/2014 0:21:00  40.7316 -73.9873  B02512
3          4/1/2014 0:28:00  40.7588 -73.9776  B02512
4          4/1/2014 0:33:00  40.7594 -73.9722  B02512
5          4/1/2014 0:33:00  40.7383 -74.0403  B02512
6          4/1/2014 0:39:00  40.7223 -73.9887  B02512
7          4/1/2014 0:45:00  40.7620 -73.9790  B02512
8          4/1/2014 0:55:00  40.7524 -73.9960  B02512
9          4/1/2014 1:01:00  40.7575 -73.9846  B02512
10         4/1/2014 1:19:00  40.7256 -73.9869  B02512
11         4/1/2014 1:48:00  40.7591 -73.9684  B02512
12         4/1/2014 1:49:00  40.7271 -73.9803  B02512
13         4/1/2014 2:11:00  40.6463 -73.7896  B02512
14         4/1/2014 2:25:00  40.7564 -73.9167  B02512
15         4/1/2014 2:31:00  40.7666 -73.9531  B02512
16         4/1/2014 2:43:00  40.7580 -73.9761  B02512
17         4/1/2014 3:22:00  40.7238 -73.9821  B02512
18         4/1/2014 3:35:00  40.7531 -74.0039  B02512
19         4/1/2014 3:35:00  40.7389 -74.0393  B02512
20         4/1/2014 3:41:00  40.7619 -73.9715  B02512
21         4/1/2014 4:11:00  40.7530 -74.0042  B02512
22         4/1/2014 4:15:00  40.6561 -73.9531  B02512
23         4/1/2014 4:19:00  40.7250 -73.9844  B02512
24         4/1/2014 4:20:00  40.6950 -74.1783  B02512
25         4/1/2014 4:26:00  40.9859 -74.1578  B02512
26         4/1/2014 4:27:00  40.6879 -74.1814  B02512
27         4/1/2014 4:38:00  40.6878 -74.1816  B02512
28         4/1/2014 4:47:00  40.7234 -73.9974  B02512
29         4/1/2014 4:49:00  40.7336 -73.9900  B02512
...                     ...      ...      ...     ...
1028106  9/30/2014 22:49:00  40.7079 -74.0061  B02764
1028107  9/30/2014 22:50:00  40.7775 -73.9468  B02764
1028108  9/30/2014 22:51:00  40.7383 -73.9923  B02764
1028109  9/30/2014 22:51:00  40.6596 -73.9479  B02764
1028110  9/30/2014 22:51:00  40.7130 -73.7976  B02764
1028111  9/30/2014 22:51:00  40.7480 -74.0007  B02764
1028112  9/30/2014 22:51:00  40.7109 -73.9337  B02764
1028113  9/30/2014 22:52:00  40.8287 -73.9488  B02764
1028114  9/30/2014 22:52:00  40.7452 -73.9278  B02764
1028115  9/30/2014 22:52:00  40.7517 -73.9866  B02764
1028116  9/30/2014 22:53:00  40.7724 -73.9587  B02764
1028117  9/30/2014 22:53:00  40.7234 -73.9913  B02764
1028118  9/30/2014 22:53:00  40.7417 -74.0038  B02764
1028119  9/30/2014 22:53:00  40.7509 -73.9785  B02764
1028120  9/30/2014 22:53:00  40.7588 -73.9721  B02764
1028121  9/30/2014 22:54:00  40.6932 -73.9693  B02764
1028122  9/30/2014 22:54:00  40.7273 -74.0057  B02764
1028123  9/30/2014 22:54:00  40.7594 -73.9820  B02764
1028124  9/30/2014 22:55:00  40.7520 -74.0027  B02764
1028125  9/30/2014 22:55:00  40.7205 -73.9571  B02764
1028126  9/30/2014 22:56:00  40.7371 -74.0289  B02764
1028127  9/30/2014 22:56:00  40.6446 -73.7823  B02764
1028128  9/30/2014 22:56:00  40.7163 -73.9623  B02764
1028129  9/30/2014 22:57:00  40.6979 -73.9365  B02764
1028130  9/30/2014 22:57:00  40.7300 -73.9565  B02764
1028131  9/30/2014 22:57:00  40.7668 -73.9845  B02764
1028132  9/30/2014 22:57:00  40.6911 -74.1773  B02764
1028133  9/30/2014 22:58:00  40.8519 -73.9319  B02764
1028134  9/30/2014 22:58:00  40.7081 -74.0066  B02764
1028135  9/30/2014 22:58:00  40.7140 -73.9496  B02764

[4534327 rows x 4 columns]